---
- name: Install required PostgreSQL packages
  package:
    name: "{{ postgresql_packages }}"
    state: present
  become: true

- name: Remove existing PostgreSQL data directory (RedHat only)
  file:
    path: "/var/lib/pgsql/data"
    state: absent
  become: true
  when: ansible_facts['os_family'] == 'RedHat'

- name: Initialize PostgreSQL database (RedHat only)
  command: "postgresql-setup --initdb --unit postgresql"
  become: true
  when: ansible_facts['os_family'] == 'RedHat'
  ignore_errors: yes

- name: Ensure PostgreSQL config directory exists
  file:
    path: "{{ postgresql_config_file | default('/etc/postgresql/14/main/postgresql.conf') | dirname }}"
    state: directory
    mode: '0755'
  become: true

- name: Configure PostgreSQL
  template:
    src: postgresql.conf.j2
    dest: "{{ postgresql_config_file | default('/etc/postgresql/14/main/postgresql.conf') }}"
  become: true
  notify:
    - restart postgresql

- name: Ensure PostgreSQL is started and enabled
  service:
    name: "{{ postgresql_service_name }}"
    state: started
    enabled: true
  become: true

- name: Configure pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
  become: true
  notify: restart postgresql
  when: ansible_facts['os_family'] == 'Debian'

- name: Configure pg_hba.conf (RedHat based)
  template:
    src: pg_hba.conf.j2
    dest: "/var/lib/pgsql/data/pg_hba.conf"
  become: true
  notify: restart postgresql
  when: ansible_facts['os_family'] == 'RedHat'
